// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybzzmutmhavqilwurajd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlienptdXRtaGF2cWlsd3VyYWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjYxNzQsImV4cCI6MjA2MzA0MjE3NH0.Fig8j6OTkdLe21y5OK-7a2_0yxrYOa_YJG--G75TArU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);